// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR4MVCTXW1tSc6NzA-FPDQ2YBlvPGzwlM',
    appId: '1:389999496094:web:7ff3d404d1565ec398a48f',
    messagingSenderId: '389999496094',
    projectId: 'hewhew-1a2f1',
    authDomain: 'hewhew-1a2f1.firebaseapp.com',
    storageBucket: 'hewhew-1a2f1.appspot.com',
    measurementId: 'G-JFG5VEBGYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa4Do8Lk1njSp2cZjcr3jKnwue5K-1w6s',
    appId: '1:389999496094:android:3d061dd90ce87e3598a48f',
    messagingSenderId: '389999496094',
    projectId: 'hewhew-1a2f1',
    storageBucket: 'hewhew-1a2f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7O3j4TGvEWe6UoeAkjXLYUPCMf2UykA4',
    appId: '1:389999496094:ios:c7ffe9b2dd36c1bc98a48f',
    messagingSenderId: '389999496094',
    projectId: 'hewhew-1a2f1',
    storageBucket: 'hewhew-1a2f1.appspot.com',
    iosClientId: '389999496094-45cdmd48u2lg9uuvvk00hkd6iob87s5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.hewhew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7O3j4TGvEWe6UoeAkjXLYUPCMf2UykA4',
    appId: '1:389999496094:ios:4c2c1b066f6ffc3e98a48f',
    messagingSenderId: '389999496094',
    projectId: 'hewhew-1a2f1',
    storageBucket: 'hewhew-1a2f1.appspot.com',
    iosClientId: '389999496094-pch00ki5b2hfmft1jehocrhopoau3cv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.hewhew.RunnerTests',
  );
}
